### ISSUE TITLE
publish step NPD

### ISSUE THREAD

**Issue by emenda-support** [Emenda/klocwork-plugin#7]
NPD when using the publish step. Note the threshold values are empty

`18:47:08 ERROR: Build step failed with exception
18:47:08 java.lang.NullPointerException
18:47:08       at com.thalesgroup.hudson.plugins.klocwork.util.KloBuildResultEvaluator.evaluateBuildResult(KloBuildResultEvaluator.java:57)
18:47:08       at com.thalesgroup.hudson.plugins.klocwork.KloPublisher.perform(KloPublisher.java:272)
18:47:08       at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
18:47:08       at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:776)
18:47:08       at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
18:47:08       at hudson.model.Build$BuildExecution.post2(Build.java:183)
18:47:08       at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
18:47:08       at hudson.model.Run.execute(Run.java:1763)
18:47:08       at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
18:47:08       at hudson.model.ResourceController.execute(ResourceController.java:98)
18:47:08       at hudson.model.Executor.run(Executor.java:381)
`

**Comment by emenda-support** [comment]
Resolved v2.1
